### ISSUE TITLE
AttributeError: MitmChannelBased instance has no attribute 'run'

### ISSUE THREAD

**Issue by KanG00** [lucascouto/krackattack-all-zero-tk-key#10]
After running command:

_sudo ./krack_all_zero_tk.py wlan0 wlan1 eth0 "xxx" -t xx:xx:xx:xx:xx:xx_

I get this error:

`WARNING: Failed to execute tcpdump. Check it is installed and in the PATH

	===[ KRACK Attacks against Linux/Android by Lucas Woody ]===

Traceback (most recent call last):
  File "./krack_all_zero_tk.py", line 593, in <module>
    attack.run(strict_echo_test=args.strict_echo_test)
  File "./krack_all_zero_tk.py", line 513, in run
    self.mitmconfig.run()
AttributeError: MitmChannelBased instance has no attribute 'run'
[23:15:48] Closing hostapd and cleaning up ...`

**Comment by taleen98** [comment]
hello @KanG00 , did u solve ur problem? if 'yes' then plz send me the solution,thanks.

**Comment by Real96** [comment]
> After running command:
> 
> _sudo ./krack_all_zero_tk.py wlan0 wlan1 eth0 "xxx" -t xx:xx:xx:xx:xx:xx_
> 
> I get this error:
> 
> `WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
> 
> ```
> ===[ KRACK Attacks against Linux/Android by Lucas Woody ]===
> ```
> 
> Traceback (most recent call last):
> File "./krack_all_zero_tk.py", line 593, in
> attack.run(strict_echo_test=args.strict_echo_test)
> File "./krack_all_zero_tk.py", line 513, in run
> self.mitmconfig.run()
> AttributeError: MitmChannelBased instance has no attribute 'run'
> [23:15:48] Closing hostapd and cleaning up ...`

Did you install tcpdump?

**Comment by maneshthankappan** [comment]
hello @Real96 , @taleen98 ,Did u solve the error posted by @KanG00 . I am getting same error. Could you help me.
@lucascouto .Hello luca,please help

**Comment by Real96** [comment]
> hello @Real96 , @taleen98 ,Did u solve the error posted by @KanG00 . I am getting same error. Could you help me.
> @lucascouto .Hello luca,please help

Did you install tcpdump?

**Comment by maneshthankappan** [comment]
@Real96. thank you for ur instant reply. yes I have installed tcpdump. I am a PhD student working on Channel MitM and experiment KRACK attacks.because of these errors, i cannot move forward. could you send me an email to me "maneshpadmayil@gmail.com".  Hoping ur email.

**Comment by Real96** [comment]
> @Real96. thank you for ur instant reply. yes I have installed tcpdump. I am a PhD student working on Channel MitM and experiment KRACK attacks.because of these errors, i cannot move forward. could you send me an email to me "[maneshpadmayil@gmail.com](mailto:maneshpadmayil@gmail.com)". Hoping ur email.

I did the attack one year ago and to make it work i had to downgrade Scapy version to 2.3.3. This was the only problem i was getting. I never got the tcpdump problem, but as the error says, you should have tcpdump installed and also in the path. Also i don't think it is so much necessary, tcpdump is needed to dump the packets, i think you can just use wireshark or something else.
If this can help you, i also used an old kali release

**Comment by maneshthankappan** [comment]
@Real96 .Thank u so much. ok. Should I check path of tcpdump? My scapy version is 2.4.2. Should I try downgrade? by the by.million thank that you considered my error. I have just followed u on twitter, could u foloow me back, so that I can discuss some of my doubts. with hope....

**Comment by Real96** [comment]
> @Real96 .Thank u so much. ok. Should I check path of tcpdump? My scapy version is 2.4.2. Should I try downgrade? by the by.million thank that you considered my error. I have just followed u on twitter, could u foloow me back, so that I can discuss some of my doubts. with hope....

I wrote you there!

**Comment by nolsie** [comment]
Downgrade Scapy and it should work.

**Comment by Real96** [comment]
> Downgrade Scapy and it should work.

Yeah, 2.3.3 made it work for me

**Comment by maneshthankappan** [comment]
@nolsie, thank you for responding. I have contacted @Real96 . He gave me instructions. I am working on it.once solved .I will post here. Thanks again.
