### ISSUE TITLE
Error while running the script. havent experienced it before

### ISSUE THREAD

**Issue by ketasic** [lucascouto/krackattack-all-zero-tk-key#3]
HI
on running the script o receive this error which i havent received before even though ive used the script multiple times. the error is :

sudo python ./krackattack/krack_all_zero_tk.py wlan2 wlan0 eth0 "testnetwork -t -----------------

	===[ KRACK Attacks against Linux/Android by Lucas Woody ]===

[10:34:27] Note: remember to disable Wi-Fi in your network manager so it doesn't interfere with this script
[10:34:27] Note: keep >1 meter between both interfaces. Else packet delivery is unreliable & target may disconnect
[10:34:29] Searching for target network on other channels
[10:34:36] Target network ----------------- detected on channel 6
[10:34:36] Will create rogue AP on channel 1
[10:34:36] Setting MAC address of wlan0 to -----------------
Traceback (most recent call last):
  File "./krackattack/krack_all_zero_tk.py", line 593, in <module>
    attack.run(strict_echo_test=args.strict_echo_test)
  File "./krackattack/krack_all_zero_tk.py", line 513, in run
    self.mitmconfig.run()
  File "/root/.local/lib/python2.7/site-packages/mitm_channel_based/mitm_code.py", line 420, in run
    subprocess.Popen(["./enable_internet_forwarding.sh", self.nic_ether, self.nic_rogue_ap], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[10:34:36] Closing hostapd and cleaning up ...

hoping you could help. ive been stuck for weeks for some reason and i just dont get it.

**Comment by ketasic** [comment]
Really sorry to bother you but the issue has been resolved. thanks anyways.
however when i run the enable_internet_forwarding.sh script with the command 
sudo ./enable_internet_forwarding.sh

 it gives me an error:
Command line is not complete. Try option "help".
where am i going wrong?

**Comment by r3dw0lf** [comment]
@ketasic What did you do. I have the same problem here, just reading python files, could you solve your problem?

**Comment by ketasic** [comment]
No sorry. Haven't been able to solve it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by r3dw0lf** [comment]
I solved the issue, The main point is that this project relies on scapy. In scapy the developer forgot to put the LICENSE file so in recent version it was not working properly. I used kali 2018.4 and after upgrading pip and setup tools to the latest it worked fine.
```
$pip install pip --upgrade
$sudo pip install setuptools --upgrade
```

**Comment by ketasic** [comment]
Oh okay
that's nice work done.
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
