### ISSUE TITLE
error while running the script

### ISSUE THREAD

**Issue by Shameel123** [lucascouto/krackattack-all-zero-tk-key#5]
./krack_all_zero_tk.py 
Traceback (most recent call last):
  File "./krack_all_zero_tk.py", line 10, in <module>
    username = os.path.expanduser(os.environ["SUDO_USER"])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SUDO_USER'

**Comment by Shameel123** [comment]
solved it myself.
By changing "SUDO_USER" to "USER"
